FROM ubuntu:focal
MAINTAINER	don.r.kabob

ENV CONFIGFILE="lotto_config.json"
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get -y update \
	&& apt-get install -y tzdata \
	&& apt-get install -y python3.9 python3-pip

RUN pip3 install virtualenv
RUN pip3 install pandas
RUN pip3 install tda-api flask
